radiopro/radiohome/urls.py
from django.urls import path
 
from . import views
 
# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'radiohome'

urlpatterns = [
    path('', views.index, name='index'),
]

radiopro/radiopro/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('radiohome.urls')),
    url(r'^upload/', include('radioupload.urls',namespace = 'radioupload')),
]

radiopro/radioupload/urls.py
from django.urls import path
from django.conf.urls import url,include
 
from . import views
 
# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'radioupload'

urlpatterns = [
    path('', views.upload, name='upload'),
    url(r'^complete/', views.complete, name = 'complete'),
    ]

radiopro/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


class User(AbstractUser):
    objects = UserManager()

    class Meta(object):
        app_label = 'accounts'

radiopro/radioupload/models.py
from django.db import models
from radiopro  import settings

# Create your models here.

from datetime import datetime


class FileModel(models.Model):

    class Meta:
        db_table = 'radiofile'

    file = models.FileField(upload_to='radiofile/')
    user = models.CharField(max_length=500, null=False)
    title = models.CharField(max_length=32, blank=False)
    description = models.CharField(max_length=255, blank=True)
    thumbnail = models.ImageField(upload_to='radiofile/')
    submitter = models.ForeignKey(settings.AUTH_USER_MODEL, models.PROTECT, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

radiopro/radioupload/forms.py
from django import forms
from radioupload.models import FileModel


class FileForm(forms.ModelForm):
    class Meta:
        model = FileModel
        fields = ('title', 'description', 'thumbnail', 'file',)

radiopro/accounts/views.py
from django.shortcuts import render

# Create your views here.

radiopro/radiohome/views.py
from django.shortcuts import render
from django.http import HttpResponse
from radioupload.models import FileModel

# Create your views here.

def index(request):
    data = FileModel.objects.all()
    params = {
        'data' : data,
    }
    return render(request, 'radiohome/index.html', params)

radiopro/radioupload/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.template.context_processors import csrf
from django.conf import settings
from radioupload.models import FileModel
from radioupload.forms import FileForm
import sys, os

UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'


# Create your views here.

@login_required
def upload(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('radioupload/complete')
    else:
        form = FileForm()
    return render(request, 'radioupload/upload.html', {
        'form': form
    })

def complete(request):
    return render(request, 'radioupload/complete.html')

radiopro/radiohome/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <!--Bootstrap４に必要なCSSとJavaScriptを読み込み-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <title></title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

radiopro/radiohome/templates/radiohome/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
<table>
    <tr>
        <th>title</th>
        <th>description</th>
        <th>thumbnail</th>
    </tr>
    {% for item in data %}
    <tr>
        <th>{{item.title}}</th>
        <th>{{item.description}}</th>
        <th>{{item.thumbnail}}</th>
    </tr>
    {% endfor %}
</table>
{% endblock %}

radiopro/radioupload/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <!--Bootstrap４に必要なCSSとJavaScriptを読み込み-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <title>ファイルアップローダ</title>
    </head>
    <body>
        {% block content %}
            {{ content }}
        {% endblock %}
    </body>
</html>

radiopro/radioupload/templates/radioupload/complete.html
{% extends "base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}
    <div align="center">
        <h1 align="center">アップロード完了</h1>
        <a href="{% url 'radioupload:upload' %}"><button>戻る</button></a>
    </div>
{% endblock content %}

radiopro/radioupload/templates/radioupload/upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
{% endblock %}

radiopro/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <!--Bootstrap４に必要なCSSとJavaScriptを読み込み-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    </head>
    <body>
        {% block content %}
            {{ content }}
        {% endblock %}
    </body>
</html>